### ISSUE TITLE
Version error doesn't allow camping calculation.

### ISSUE THREAD

**Issue by l-l-l-l-l-l** [zerah54/MyHordesOptimizer#57]
Yesterday or thereabouts I received a notification saying that there was an update for MHO script. When I tried updating it, it told me that the latest version was 1.0.30.0, the same one I've currently installed, so false warning.

I need to use the camping calculator, but every time it tries to do a calculation, I get a pop-up error message saying that my script with version 1.0.30.0 is not up to date, that the most recently updated version is 1.0.0.1, so it won't work.

**Comment by zerah54** [comment]
In database, the current version was 1.0.0.1 instead of 1.0.30.0
Fixed
